### ISSUE TITLE
Conflicting stamps between overview and detailed

### ISSUE THREAD

**Issue by itsadok** [akariv/gov-watch#10]
It looks like the problem is the following sections:
in style-overview.less: 

``` css
    &.notstarted{
      background: url("/static/img/stamp-new.png");
    }

    &.late{
      background: url("/static/img/stamp-stuck.png");
    }
```

in style-details.less:

``` css

    &.late,
    &.notstarted{
      background: url("/static/img/stamp-late.png");
    }
```

I suspect neither is correct...
